import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from "react-hot-toast";
import TanStackProvider from '@/components/Provider';
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from './api/uploadthing/core';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChatPdf SaaS Platform',
  description: 'Generated by Rakibul hasan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <TanStackProvider>{children}</TanStackProvider>
        </body>
        <Toaster />
      </html>
    </ClerkProvider >
  )
}
