import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import ProviderLayout from '@/components/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChatPdf SaaS Platform',
  description: 'Generated by Rakibul hasan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <ProviderLayout>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ProviderLayout >
    </ClerkProvider>
  )
}
